# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'laba_ira_1.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AtbashForm(object):
    def setupUi(self, AtbashForm):
        AtbashForm.setObjectName("AtbashForm")
        AtbashForm.resize(900, 800)
        self.gridLayout_2 = QtWidgets.QGridLayout(AtbashForm)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.inputLabel = QtWidgets.QLabel(AtbashForm)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.inputLabel.setFont(font)
        self.inputLabel.setMidLineWidth(1)
        self.inputLabel.setTextFormat(QtCore.Qt.AutoText)
        self.inputLabel.setObjectName("inputLabel")
        self.horizontalLayout.addWidget(self.inputLabel)
        self.openBut = QtWidgets.QPushButton(AtbashForm)
        self.openBut.setObjectName("openBut")
        self.horizontalLayout.addWidget(self.openBut)
        self.ClearBut = QtWidgets.QPushButton(AtbashForm)
        self.ClearBut.setObjectName("ClearBut")
        self.horizontalLayout.addWidget(self.ClearBut)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.textEdit = QtWidgets.QTextEdit(AtbashForm)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_3.addWidget(self.textEdit)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.outputLabel = QtWidgets.QLabel(AtbashForm)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.outputLabel.setFont(font)
        self.outputLabel.setMidLineWidth(1)
        self.outputLabel.setTextFormat(QtCore.Qt.AutoText)
        self.outputLabel.setObjectName("outputLabel")
        self.horizontalLayout_2.addWidget(self.outputLabel)
        self.CalcBut = QtWidgets.QPushButton(AtbashForm)
        self.CalcBut.setObjectName("CalcBut")
        self.horizontalLayout_2.addWidget(self.CalcBut)
        self.SaveBut = QtWidgets.QPushButton(AtbashForm)
        self.SaveBut.setObjectName("SaveBut")
        self.horizontalLayout_2.addWidget(self.SaveBut)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.textBrowser = QtWidgets.QTextBrowser(AtbashForm)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_4.addWidget(self.textBrowser)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.fileButton = QtWidgets.QRadioButton(AtbashForm)
        self.fileButton.setObjectName("fileButton")
        self.horizontalLayout_5.addWidget(self.fileButton)
        self.wikiButton = QtWidgets.QRadioButton(AtbashForm)
        self.wikiButton.setObjectName("wikiButton")
        self.horizontalLayout_5.addWidget(self.wikiButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.adressButton = QtWidgets.QPushButton(AtbashForm)
        self.adressButton.setObjectName("adressButton")
        self.horizontalLayout_6.addWidget(self.adressButton)
        self.saveFreqButton = QtWidgets.QPushButton(AtbashForm)
        self.saveFreqButton.setObjectName("saveFreqButton")
        self.horizontalLayout_6.addWidget(self.saveFreqButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(AtbashForm)
        self.lineEdit.setMinimumSize(QtCore.QSize(350, 0))
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(AtbashForm)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.OneKeyBut = QtWidgets.QPushButton(AtbashForm)
        self.OneKeyBut.setObjectName("OneKeyBut")
        self.verticalLayout_2.addWidget(self.OneKeyBut)
        self.TwoKeyBut = QtWidgets.QPushButton(AtbashForm)
        self.TwoKeyBut.setObjectName("TwoKeyBut")
        self.verticalLayout_2.addWidget(self.TwoKeyBut)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(AtbashForm)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(AtbashForm)
        QtCore.QMetaObject.connectSlotsByName(AtbashForm)

    def retranslateUi(self, AtbashForm):
        _translate = QtCore.QCoreApplication.translate
        AtbashForm.setWindowTitle(_translate("AtbashForm", "Частотный криптоанализ"))
        self.inputLabel.setText(_translate("AtbashForm", "Исходный текст:"))
        self.openBut.setText(_translate("AtbashForm", "Открыть"))
        self.ClearBut.setText(_translate("AtbashForm", "Очистить"))
        self.outputLabel.setText(_translate("AtbashForm", "Результат:"))
        self.CalcBut.setText(_translate("AtbashForm", "Рассчитать"))
        self.SaveBut.setText(_translate("AtbashForm", "Сохранить"))
        self.fileButton.setText(_translate("AtbashForm", "С файла"))
        self.wikiButton.setText(_translate("AtbashForm", "С википедии"))
        self.adressButton.setText(_translate("AtbashForm", "Выбрать"))
        self.saveFreqButton.setText(_translate("AtbashForm", "Сохранить"))
        self.OneKeyBut.setText(_translate("AtbashForm", "Применить"))
        self.TwoKeyBut.setText(_translate("AtbashForm", "Применить"))

