# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'laba_ira.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AtbashForm(object):
    def setupUi(self, AtbashForm):
        AtbashForm.setObjectName("AtbashForm")
        AtbashForm.resize(745, 686)
        self.textEdit = QtWidgets.QTextEdit(AtbashForm)
        self.textEdit.setGeometry(QtCore.QRect(10, 40, 341, 192))
        self.textEdit.setObjectName("textEdit")
        self.textBrowser = QtWidgets.QTextBrowser(AtbashForm)
        self.textBrowser.setGeometry(QtCore.QRect(390, 40, 341, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.inputLabel = QtWidgets.QLabel(AtbashForm)
        self.inputLabel.setGeometry(QtCore.QRect(9, 9, 115, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.inputLabel.setFont(font)
        self.inputLabel.setMidLineWidth(1)
        self.inputLabel.setTextFormat(QtCore.Qt.AutoText)
        self.inputLabel.setObjectName("inputLabel")
        self.outputLabel = QtWidgets.QLabel(AtbashForm)
        self.outputLabel.setGeometry(QtCore.QRect(390, 10, 72, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.outputLabel.setFont(font)
        self.outputLabel.setMidLineWidth(1)
        self.outputLabel.setTextFormat(QtCore.Qt.AutoText)
        self.outputLabel.setObjectName("outputLabel")
        self.ClearBut = QtWidgets.QPushButton(AtbashForm)
        self.ClearBut.setGeometry(QtCore.QRect(260, 10, 84, 28))
        self.ClearBut.setObjectName("ClearBut")
        self.CalcBut = QtWidgets.QPushButton(AtbashForm)
        self.CalcBut.setGeometry(QtCore.QRect(560, 10, 84, 28))
        self.CalcBut.setObjectName("CalcBut")
        self.lineEdit = QtWidgets.QLineEdit(AtbashForm)
        self.lineEdit.setGeometry(QtCore.QRect(390, 250, 251, 28))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(AtbashForm)
        self.lineEdit_2.setGeometry(QtCore.QRect(390, 290, 251, 28))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(AtbashForm)
        self.lineEdit_3.setGeometry(QtCore.QRect(390, 330, 251, 28))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.OneKeyBut = QtWidgets.QPushButton(AtbashForm)
        self.OneKeyBut.setGeometry(QtCore.QRect(650, 250, 81, 28))
        self.OneKeyBut.setObjectName("OneKeyBut")
        self.TwoKeyBut = QtWidgets.QPushButton(AtbashForm)
        self.TwoKeyBut.setGeometry(QtCore.QRect(650, 290, 81, 28))
        self.TwoKeyBut.setObjectName("TwoKeyBut")
        self.ThreeKetBut = QtWidgets.QPushButton(AtbashForm)
        self.ThreeKetBut.setGeometry(QtCore.QRect(650, 330, 81, 28))
        self.ThreeKetBut.setObjectName("ThreeKetBut")
        self.pogreshnostBut = QtWidgets.QLineEdit(AtbashForm)
        self.pogreshnostBut.setGeometry(QtCore.QRect(10, 290, 113, 28))
        self.pogreshnostBut.setObjectName("pogreshnostBut")
        self.label = QtWidgets.QLabel(AtbashForm)
        self.label.setGeometry(QtCore.QRect(10, 260, 111, 20))
        self.label.setObjectName("label")
        self.BigramCheck = QtWidgets.QCheckBox(AtbashForm)
        self.BigramCheck.setGeometry(QtCore.QRect(10, 340, 91, 26))
        self.BigramCheck.setObjectName("BigramCheck")
        self.ThreegramCheck = QtWidgets.QCheckBox(AtbashForm)
        self.ThreegramCheck.setGeometry(QtCore.QRect(10, 370, 111, 26))
        self.ThreegramCheck.setObjectName("ThreegramCheck")
        self.SymbolCheck = QtWidgets.QCheckBox(AtbashForm)
        self.SymbolCheck.setGeometry(QtCore.QRect(200, 370, 161, 21))
        self.SymbolCheck.setObjectName("SymbolCheck")
        self.DangerCheck = QtWidgets.QCheckBox(AtbashForm)
        self.DangerCheck.setGeometry(QtCore.QRect(10, 400, 191, 26))
        self.DangerCheck.setObjectName("DangerCheck")
        self.LanguageCheck = QtWidgets.QCheckBox(AtbashForm)
        self.LanguageCheck.setGeometry(QtCore.QRect(200, 340, 121, 26))
        self.LanguageCheck.setObjectName("LanguageCheck")
        self.openBut = QtWidgets.QPushButton(AtbashForm)
        self.openBut.setGeometry(QtCore.QRect(170, 10, 84, 28))
        self.openBut.setObjectName("openBut")
        self.tableWidget = QtWidgets.QTableWidget(AtbashForm)
        self.tableWidget.setGeometry(QtCore.QRect(20, 460, 256, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        self.graphicsView = QtWidgets.QGraphicsView(AtbashForm)
        self.graphicsView.setGeometry(QtCore.QRect(420, 420, 256, 192))
        self.graphicsView.setObjectName("graphicsView")
        self.SaveBut = QtWidgets.QPushButton(AtbashForm)
        self.SaveBut.setGeometry(QtCore.QRect(650, 10, 84, 28))
        self.SaveBut.setObjectName("SaveBut")

        self.retranslateUi(AtbashForm)
        QtCore.QMetaObject.connectSlotsByName(AtbashForm)

    def retranslateUi(self, AtbashForm):
        _translate = QtCore.QCoreApplication.translate
        AtbashForm.setWindowTitle(_translate("AtbashForm", "Частотный криптоанализ"))
        self.inputLabel.setText(_translate("AtbashForm", "Исходный текст:"))
        self.outputLabel.setText(_translate("AtbashForm", "Результат:"))
        self.ClearBut.setText(_translate("AtbashForm", "Очистить"))
        self.CalcBut.setText(_translate("AtbashForm", "Рассчитать"))
        self.OneKeyBut.setText(_translate("AtbashForm", "Применить"))
        self.TwoKeyBut.setText(_translate("AtbashForm", "Применить"))
        self.ThreeKetBut.setText(_translate("AtbashForm", "Применить"))
        self.label.setText(_translate("AtbashForm", "Погрешность"))
        self.BigramCheck.setText(_translate("AtbashForm", "биграммы"))
        self.ThreegramCheck.setText(_translate("AtbashForm", "триграммы"))
        self.SymbolCheck.setText(_translate("AtbashForm", "одиночные символы"))
        self.DangerCheck.setText(_translate("AtbashForm", "запрещенные сочетания"))
        self.LanguageCheck.setText(_translate("AtbashForm", "правила языка"))
        self.openBut.setText(_translate("AtbashForm", "Открыть"))
        self.SaveBut.setText(_translate("AtbashForm", "Сохранить"))

